//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reti.NewCondeco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewCondecoEntities : DbContext
    {
        public NewCondecoEntities()
            : base("name=NewCondecoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
    }
}
