//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reti.NewCondeco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomId { get; set; }
        public string Name { get; set; }
        public int AvaiableSeats { get; set; }
        public int RoomBuildingId { get; set; }
        public bool IsAvaible { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
