
USE [master]
GO

/****** Object:  Database [NewCondeco]    Script Date: 21/08/2019 18:45:49 ******/
CREATE DATABASE [NewCondeco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewCondeco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\NewCondeco.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewCondeco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\NewCondeco_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NewCondeco] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewCondeco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewCondeco] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [NewCondeco] SET ANSI_NULLS OFF
GO

ALTER DATABASE [NewCondeco] SET ANSI_PADDING OFF
GO

ALTER DATABASE [NewCondeco] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [NewCondeco] SET ARITHABORT OFF
GO

ALTER DATABASE [NewCondeco] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [NewCondeco] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [NewCondeco] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [NewCondeco] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [NewCondeco] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [NewCondeco] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [NewCondeco] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [NewCondeco] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [NewCondeco] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [NewCondeco] SET  DISABLE_BROKER
GO

ALTER DATABASE [NewCondeco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [NewCondeco] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [NewCondeco] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [NewCondeco] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [NewCondeco] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [NewCondeco] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [NewCondeco] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [NewCondeco] SET RECOVERY SIMPLE
GO

ALTER DATABASE [NewCondeco] SET  MULTI_USER
GO

ALTER DATABASE [NewCondeco] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [NewCondeco] SET DB_CHAINING OFF
GO

ALTER DATABASE [NewCondeco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [NewCondeco] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [NewCondeco] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [NewCondeco] SET QUERY_STORE = OFF
GO

USE [NewCondeco]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [NewCondeco]
GO

/****** Object:  Table [dbo].[Booking]    Script Date: 21/08/2019 18:45:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Buildings]    Script Date: 21/08/2019 18:45:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Resources]    Script Date: 21/08/2019 18:45:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Rooms]    Script Date: 21/08/2019 18:45:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [NewCondeco] SET  READ_WRITE
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;

GO

--Syntax Error: Incorrect syntax near IDENTITY_CACHE.
--ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;



GO

USE [master]
GO

/****** Object:  Database [NewCondeco]    Script Date: 31/08/2019 20:33:09 ******/
CREATE DATABASE [NewCondeco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewCondeco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\NewCondeco.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewCondeco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\NewCondeco_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NewCondeco] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewCondeco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewCondeco] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [NewCondeco] SET ANSI_NULLS OFF
GO

ALTER DATABASE [NewCondeco] SET ANSI_PADDING OFF
GO

ALTER DATABASE [NewCondeco] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [NewCondeco] SET ARITHABORT OFF
GO

ALTER DATABASE [NewCondeco] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [NewCondeco] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [NewCondeco] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [NewCondeco] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [NewCondeco] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [NewCondeco] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [NewCondeco] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [NewCondeco] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [NewCondeco] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [NewCondeco] SET  DISABLE_BROKER
GO

ALTER DATABASE [NewCondeco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [NewCondeco] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [NewCondeco] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [NewCondeco] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [NewCondeco] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [NewCondeco] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [NewCondeco] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [NewCondeco] SET RECOVERY SIMPLE
GO

ALTER DATABASE [NewCondeco] SET  MULTI_USER
GO

ALTER DATABASE [NewCondeco] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [NewCondeco] SET DB_CHAINING OFF
GO

ALTER DATABASE [NewCondeco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [NewCondeco] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [NewCondeco] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [NewCondeco] SET QUERY_STORE = OFF
GO

USE [NewCondeco]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [NewCondeco]
GO

/****** Object:  Table [dbo].[Booking]    Script Date: 31/08/2019 20:33:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Buildings]    Script Date: 31/08/2019 20:33:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Resources]    Script Date: 31/08/2019 20:33:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Rooms]    Script Date: 31/08/2019 20:33:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [NewCondeco] SET  READ_WRITE
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;

GO

--Syntax Error: Incorrect syntax near IDENTITY_CACHE.
--ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;



GO
